# Generated by Django 6.0.2 on 2026-04-12 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSource',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField()),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('film', models.ForeignKey(db_column='film_id', on_delete=django.db.models.deletion.CASCADE, to='movies.film')),
            ],
            options={
                'verbose_name': 'Resena',
                'verbose_name_plural': 'Resenas',
                'db_table': 'review',
            },
        ),
    ]
