# Generated by Django 6.0.2 on 2026-04-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('rental_duration', models.IntegerField()),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.IntegerField()),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('special_features', models.JSONField(blank=True, null=True)),
                ('fulltext', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
